# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-06 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chouti', '0002_news_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='source',
            field=models.CharField(default='unkonow', max_length=32),
        ),
    ]
