# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-06 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chouti', '0003_news_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='ctime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
