# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-08 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chouti', '0004_auto_20170606_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.TextField(default=None, max_length=65535),
        ),
    ]
