# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-07 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32)),
                ('author', models.CharField(max_length=32)),
                ('price', models.FloatField(null=True)),
                ('pub_date', models.DateField(null=True)),
            ],
        ),
    ]
