# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-09 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='pub_date',
            field=models.CharField(max_length=32),
        ),
    ]
