# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-20 06:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20170520_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='u2g',
            name='ug',
        ),
        migrations.RemoveField(
            model_name='u2g',
            name='ui',
        ),
        migrations.DeleteModel(
            name='U2G',
        ),
    ]
