# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_newassetapprovalzone'),
    ]

    operations = [
        migrations.AddField(
            model_name='disk',
            name='manufactory',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='制造商'),
        ),
        migrations.AlterField(
            model_name='server',
            name='raid_type',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='raid类型'),
        ),
    ]
