# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-06 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='pub_date',
            field=models.DateField(null=True),
        ),
    ]
