# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-28 08:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='ut',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='app01.UserType'),
        ),
    ]
