# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-20 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20170520_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='m',
            field=models.ManyToManyField(to='app01.UserInfo'),
        ),
    ]
