# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-10 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': '评论表'},
        ),
        migrations.AlterModelOptions(
            name='favor',
            options={'verbose_name_plural': '点赞表'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': '新闻表'},
        ),
        migrations.AlterModelOptions(
            name='newstype',
            options={'verbose_name_plural': '新闻类型表'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name_plural': '用户表'},
        ),
        migrations.RemoveField(
            model_name='news',
            name='comment_count',
        ),
        migrations.RemoveField(
            model_name='news',
            name='favor_count',
        ),
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
