# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-10 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_auto_20170610_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='news',
            name='favor_count',
            field=models.IntegerField(default=0),
        ),
    ]
