# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-14 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0006_auto_20170614_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favor',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
