# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20170805_1202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'permissions': (('luffyadmin_table_index', '可以查看所有的luffyadmin的app'), ('luffyadmin_table_list', '可以查看每张表里所有的数据'), ('luffyadmin_table_list_view', '可以访问表里每条数据的修改页'), ('luffyadmin_table_list_change', '可以对表里的每条数据进行修改'))},
        ),
        migrations.AlterField(
            model_name='account',
            name='is_staff',
            field=models.BooleanField(default=True, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
