# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-20 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=32)),
                ('m', models.ManyToManyField(to='app01.UserInfo')),
            ],
        ),
    ]
