language: python
sudo: false
cache:
  directories:
    - $HOME/.cache/pip
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy-5.6.0"
install:
  # Self-install for setup.py-driven deps
  - pip install -e .
  # Dev (doc/test running) requirements
  - pip install codecov # For codecov specifically
  - pip install -r dev-requirements.txt
script:
  # Main tests, w/ coverage!
  - inv test --coverage
  # Ensure documentation builds, both sites, maxxed nitpicking
  - inv sites
  # flake8 is now possible!
  - flake8
notifications:
  irc:
    channels: "irc.freenode.org#paramiko"
    template:
      - "%{repository}@%{branch}: %{message} (%{build_url})"
    on_success: change
    on_failure: change
  email: false
after_success:
  - codecov
