# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-14 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_auto_20170614_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='ctime',
            field=models.DateTimeField(),
        ),
    ]
