# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 07:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jumpserver', '0005_task_tasklog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='bind_hosts',
        ),
    ]
