# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20170805_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_staff2',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
