# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 04:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_account_is_staff2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_staff2',
            new_name='is_staff',
        ),
    ]
