# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-01 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_newassetapprovalzone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
