# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-31 04:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bussiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bussline', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=32)),
                ('port', models.CharField(default=22, max_length=6)),
                ('hostuser', models.CharField(default='root', max_length=16)),
                ('hostpass', models.CharField(default='123456', max_length=16)),
                ('bussiness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Bussiness')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='hosts',
            name='user',
            field=models.ManyToManyField(to='app01.Users'),
        ),
    ]
