# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 09:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jumpserver', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hostuser',
            unique_together=set([('username', 'password')]),
        ),
    ]
